# Generated by Django 3.0.8 on 2020-12-04 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('LifeStyle', 'LifeStyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology')], max_length=100)),
                ('body', models.TextField()),
                ('blog_image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('date_posted', models.DateField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
